#cloud-config
package_update: true
package_upgrade: true
package_reboot_if_required: true

packages:
  - qemu-guest-agent
  - vim
  - curl
  - git
  - auditd
  - openssh-server

runcmd:
  - systemctl enable ssh
  - systemctl start ssh
